# Generated by Django 5.1 on 2024-10-05 07:58

from django.db import migrations, models
import django.utils.timezone as timezone  # Import timezone utility for default datetime

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_interfaith',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('interfaith', 'Interfaith')], default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(null=True, blank=True),  # Allow null and blank for optional field
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_deadline',
            field=models.DateTimeField(null=True, blank=True, default=timezone.now),  # Set default to current time, and allow null
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]

