# Generated by Django 5.1 on 2024-10-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_community_is_interfaith_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
