# Generated by Django 5.1 on 2024-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('interfaith', 'Interfaith')], default='public', max_length=100),
        ),
    ]
