# Generated by Django 5.1 on 2024-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('interfaith', 'Interfaith')], default='public', max_length=10),
        ),
    ]
