# Generated by Django 5.1 on 2024-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_max_participants_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
