# Generated by Django 5.1 on 2024-10-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='two_fa_secret',
        ),
    ]
