# Generated by Django 5.1 on 2024-10-10 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_notification_community_notification_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('spiritual', 'Spiritual'), ('financial', 'Financial'), ('emotional', 'Emotional')], max_length=255)),
                ('description', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='volunteerhistory',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='volunteerhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='volunteerhistory',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='volunteerhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos/'),
        ),
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='events.community'),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='partnership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='volunteerhistory',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.activity'),
        ),
        migrations.AddField(
            model_name='volunteerhistory',
            name='hours',
            field=models.PositiveIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerhistory',
            name='volunteer_name',
            field=models.CharField(default='Unknown Volunteer', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('poll', 'user')},
        ),
    ]
