# Generated by Django 5.1 on 2024-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_helprequest_rename_event_date_volunteerhistory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='user_name',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health Support'), ('food_assistance', 'Food Assistance'), ('shelter_services', 'Shelter Services'), ('educational_support', 'Educational Support')], max_length=50),
        ),
    ]
