# Generated by Django 5.1 on 2024-10-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_helprequest_user_name_helprequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
