# Generated by Django 5.1 on 2024-10-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_helprequest_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='address',
            field=models.CharField(default=(2023, 1, 10), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='community_type',
            field=models.CharField(choices=[('Religious', 'Religious'), ('Social', 'Social'), ('Educational', 'Educational')], default=(2024, 4, 14), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='contact_email',
            field=models.EmailField(default=(2024, 7, 10), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='contact_phone',
            field=models.CharField(default=(2024, 1, 12), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(default=(2024, 5, 13), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='map_location',
            field=models.URLField(default=(2024, 4, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='community_profiles/'),
        ),
        migrations.AddField(
            model_name='community',
            name='suggest_members',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='worship_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='worship_house_name',
            field=models.CharField(default=(2024, 4, 17), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
